# Generated by Django 5.2 on 2025-04-30 01:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rating',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='text',
            field=models.TextField(blank=True, default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'event', 'is_current')},
        ),
    ]
