# Generated by Django 5.2 on 2025-04-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='contact',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
