# Generated by Django 5.2 on 2025-04-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment'),
        ('app', '0004_ticket'),
    ]

    operations = [
    ]
