# Generated by Django 5.2 on 2025-04-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_refundrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='reason',
            field=models.CharField(max_length=100),
        ),
    ]
