# Generated by Django 5.2 on 2025-04-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_0004_comment_0004_ticket'),
        ('app', '0005_refundrequest_details_alter_refundrequest_reason'),
    ]

    operations = [
    ]
