# Generated by Django 5.2 on 2025-04-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_rating_unique_together_rating_is_current_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(condition=models.Q(('bl_baja', False), ('is_current', True)), fields=('user', 'event'), name='unique_active_rating_per_user_event'),
        ),
    ]
