# Generated by Django 5.2 on 2025-04-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_venue_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
