# Generated by Django 5.2 on 2025-05-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_event_category_event_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='category_events', to='app.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='events_categories', to='app.category'),
        ),
    ]
