# Generated by Django 5.2 on 2025-04-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_venue_capacity'),
        ('app', '0007_merge_20250430_0748'),
    ]

    operations = [
    ]
