# Generated by Django 5.2 on 2025-05-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20250430_0943'),
        ('app', '0010_alter_event_venue'),
    ]

    operations = [
    ]
