# Generated by Django 5.2 on 2025-05-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_merge_0006_merge_20250430_0943_0010_alter_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='reason',
            field=models.CharField(choices=[('no_asistencia', 'Impedimento para asistir'), ('evento_cancelado', 'Evento modificado'), ('error_compra', 'Error en la compra')], max_length=100),
        ),
    ]
