# Generated by Django 5.1.1 on 2025-05-03 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_category_events_alter_event_categories'),
        ('app', '0013_remove_refundrequest_approved_refundrequest_status'),
    ]

    operations = [
    ]
