# Generated by Django 5.2 on 2025-05-17 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_merge_20250502_1909'),
        ('app', '0014_merge_20250502_2128'),
    ]

    operations = [
    ]
