# Generated by Django 5.2 on 2025-05-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20250517_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado'), ('reprogramado', 'Reprogramado'), ('agotado', 'Agotado'), ('finalizado', 'Finalizado')], default='activo', max_length=20),
        ),
    ]
