# Generated by Django 5.2 on 2025-05-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Cancelado', 'Cancelado'), ('Reprogramado', 'Reprogramado'), ('Agotado', 'Agotado'), ('Finalizado', 'Finalizado')], default='Activo', max_length=20),
        ),
    ]
