name: Integracion continua

on:
  push:
    branches: ["main", "develop"]
  pull_request:
  release:
    types: [published]

jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install production dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  unit_integration_tests:
    name: Unit and Integration Tests
    runs-on: ubuntu-latest
    environment: entorno  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Export Django Secret Key
        run: echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> $GITHUB_ENV

      - name: Run unit and integration tests
        run: python manage.py test app/test/test_unit app/test/test_integration
        
  e2e_tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    environment: entorno
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright and dependencies
        run: |
          pip install playwright
          playwright install --with-deps

      - name: Export Django Secret Key
        run: echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> $GITHUB_ENV

      - name: Run E2E tests
        run: python manage.py test app/test/test_e2e
